/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package irrgarten.UI;

import irrgarten.GameState;
import irrgarten.Directions;
import javax.swing.JFrame; // Para setDefaultCloseOperation

/**
 *
 * @author Joaquín Cruz Lorenzo
 */
public class GraphicalUI extends javax.swing.JFrame implements UI {
    
    // ATRIBUTO NUEVO: La ventana para elegir dirección
    private Cursors cursors;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GraphicalUI.class.getName());

    /**
     * Creates new form GraphicalUI
     */
    public GraphicalUI() {
        initComponents();
        
        // CONFIGURACIÓN ADICIONAL
        this.setVisible(true); // Hacemos visible la ventana al crearla
        this.setLocationRelativeTo(null); // Centrar en la pantalla
        
        // Inicializamos el diálogo de cursores (this es el padre, true es modal)
        this.cursors = new Cursors(this, true);
    }
    
    /**
     * IMPLEMENTACIÓN DE UI: Muestra el estado del juego
     */
    @Override
    public void showGame(GameState gameState) {
        // 1. Actualizamos el laberinto
        this.textAreaLabyrinth.setText(gameState.getLabyrinth());
        
        // 2. Actualizamos el resto de información (Jugadores, Monstruos, Log)
        String info = "--- JUGADORES ---\n" + gameState.getPlayers() + 
                      "\n--- MONSTRUOS ---\n" + gameState.getMonsters() +
                      "\n--- LOG ---\n" + gameState.getLog();
        this.textAreaOutput.setText(info);
        
        // 3. Actualizamos etiquetas de turno y ganador
        this.labelCurrentPlayer.setText("Jugador " + gameState.getCurrentPlayer());
        
        if (gameState.isWinner()) {
            this.labelWinner.setText("El jugador " + gameState.getCurrentPlayer() + " ha ganado :)");
        } else {
            this.labelWinner.setText("No hay ganador aún");
        }
        
        // Refrescamos la vista por si acaso
        this.repaint();
    }
    
    /**
     * IMPLEMENTACIÓN DE UI: Pide el siguiente movimiento
     */
    @Override
    public Directions nextMove() {
        // Delegamos en tu ventanita Cursors
        return this.cursors.getDirection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelCurrentPlayer = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelWinner = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaLabyrinth = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaOutput = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("IRRGARTEN");

        jLabel2.setText("Turno:");

        labelCurrentPlayer.setText("jLabel3");

        jLabel3.setText("Ganador:");

        labelWinner.setText("jLabel4");

        textAreaLabyrinth.setColumns(20);
        textAreaLabyrinth.setFont(new java.awt.Font("Courier 10 Pitch", 0, 15)); // NOI18N
        textAreaLabyrinth.setRows(5);
        jScrollPane1.setViewportView(textAreaLabyrinth);

        textAreaOutput.setColumns(20);
        textAreaOutput.setRows(5);
        jScrollPane2.setViewportView(textAreaOutput);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(175, 175, 175)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 472, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(labelCurrentPlayer))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelWinner))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(labelCurrentPlayer))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(labelWinner)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraphicalUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraphicalUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraphicalUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraphicalUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GraphicalUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelCurrentPlayer;
    private javax.swing.JLabel labelWinner;
    private javax.swing.JTextArea textAreaLabyrinth;
    private javax.swing.JTextArea textAreaOutput;
    // End of variables declaration//GEN-END:variables
}
